### ISSUE TITLE
Add new slots

### ISSUE THREAD

**Issue by VisheshBansal** [CartelProject/VITable-backend#2]
Need latest slots for new subjects

**Comment by saintwithataint** [comment]
Check [this file](https://github.com/saintwithataint/VITable-backend/blob/main/slots.py), we just have to ask a junior to give us an excel file of their courses from "My Curriculum" section on VTOP using [this extension](https://chrome.google.com/webstore/detail/table-capture/iebpjdmgckacbodjpijphcplhebcmeop).

**Comment by saintwithataint** [comment]
I am currently missing some new courses which you have like ARB1001, so if a junior gives us the excel files, the [makeJson()](https://github.com/saintwithataint/VITable-backend/blob/57fd374c3782e0d6071c97e3ae6f87776755e194/slots.py#L9) function will automatically generate the courseDict for us.

**Comment by VisheshBansal** [comment]
> I am currently missing some new courses which you have like ARB1001, so if a junior gives us the excel files, the [makeJson()](https://github.com/saintwithataint/VITable-backend/blob/57fd374c3782e0d6071c97e3ae6f87776755e194/slots.py#L9) function will automatically generate the courseDict for us.

Have you tested it out properly?

**Comment by gaganmalvi** [comment]
He has afaik.

**Comment by VisheshBansal** [comment]
Cool, @saintwithataint make a pr in that case, I'll merge.

**Comment by saintwithataint** [comment]
> Have you tested it out properly?

What sort of testing? I know that it returns the same courseDict except for the ARB1001 etc courses in it. Are there some explicit tests you want me to do?

**Comment by VisheshBansal** [comment]
> > Have you tested it out properly?
> 
> What sort of testing? I know that it returns the same courseDict except for the ARB1001 etc courses in it. Are there some explicit tests you want me to do?

I meant, have you checked for breaking changes?

**Comment by saintwithataint** [comment]
> Check [this file](https://github.com/saintwithataint/VITable-backend/blob/main/slots.py?rgh-link-date=2021-12-31T04%3A40%3A51Z), we just have to ask a junior to give us an excel file of their courses from "My Curriculum" section on VTOP using [this extension](https://chrome.google.com/webstore/detail/table-capture/iebpjdmgckacbodjpijphcplhebcmeop).

@cr-trojan23 could you please make the excel files and give them to me.

**Comment by cr-trojan23** [comment]
> > Check [this file](https://github.com/saintwithataint/VITable-backend/blob/main/slots.py?rgh-link-date=2021-12-31T04%3A40%3A51Z), we just have to ask a junior to give us an excel file of their courses from "My Curriculum" section on VTOP using [this extension](https://chrome.google.com/webstore/detail/table-capture/iebpjdmgckacbodjpijphcplhebcmeop).
> 
> @cr-trojan23 could you please make the excel files and give them to me.

I'm not a fresher

**Comment by gaganmalvi** [comment]
Welp, the API is dead.

**Comment by actuallyaryaman** [comment]
added latest slots/courses
